# Generated by Django 5.1.6 on 2025-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_app', '0002_migrantworker_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
