# Generated by Django 5.1.6 on 2025-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_app', '0003_aadhaardatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardatabase',
            name='date_of_birth',
            field=models.CharField(max_length=10),
        ),
    ]
