# Generated by Django 5.1.6 on 2025-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrant_app', '0004_alter_aadhaardatabase_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrantworker',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrantworker',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
